### ISSUE TITLE
touble in paradise

### ISSUE THREAD

**Issue by jazzmonger** [kovrom/willow-autocorrect#1]
ok, I'm not a total idiot, but I am getting errors.  I copied your repo.

```
root@willow:/home/jeff/willow-autocorrect-main# ./utils.sh run                                                                                                  
Using configuration overrides from .env file
docker: Error response from daemon: driver failed programming external connectivity on endpoint wac (9a5655a37c9c41feb27ca6238e5b3bf1dd5d38f46426d0d7dc48a355bcf90d24): Bind for 0.0.0.0:9000 failed: port is already allocated.
root@willow:/home/jeff/willow-autocorrect-main# sudo nautilis
sudo: nautilis: command not found
root@willow:/home/jeff/willow-autocorrect-main# sudo nautilas
sudo: nautilas: command not found
root@willow:/home/jeff/willow-autocorrect-main# pico utils.sh
root@willow:/home/jeff/willow-autocorrect-main# pico .env
root@willow:/home/jeff/willow-autocorrect-main# ./utils.sh run
Using configuration overrides from .env file
2023-12-27 21:40:25 INFO     Set log level DEBUG
[2023-12-27T21:40:25] INFO:     Started server process [8]
[2023-12-27T21:40:25] INFO:     Waiting for application startup.
2023-12-27 21:40:25 INFO     Starting Typesense
2023-12-27 21:40:25 INFO     Typesense started. Waiting for ready...
Log directory is configured as: /dev/shm
E20231227 21:40:26.644956    99 raft_server.cpp:619] Node not ready yet (known_applied_index is 0).
E20231227 21:40:26.645063   118 raft_server.h:62] Peer refresh failed, error: Doing another configuration change
2023-12-27 21:40:35 INFO     WAC collection 'commands' not found. Initializing with timeout 120 - please wait.
[2023-12-27T21:42:49] ERROR:    Traceback (most recent call last):
  File "/app/wac.py", line 277, in init_typesense
    typesense_client.collections[COLLECTION].retrieve()
  File "/usr/local/lib/python3.12/site-packages/typesense/collection.py", line 19, in retrieve
    return self.api_call.get(self._endpoint_path())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/typesense/api_call.py", line 146, in get
    return self.make_request(session.get, endpoint, as_json,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/typesense/api_call.py", line 116, in make_request
    raise ApiCall.get_exception(r.status_code)(r.status_code, error_message)
typesense.exceptions.ObjectNotFound: [Errno 404] Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/app/wac.py", line 295, in startup_event
    init_typesense()
  File "/app/wac.py", line 282, in init_typesense
    slow_typesense_client.collections.create(wac_commands_schema)
  File "/usr/local/lib/python3.12/site-packages/typesense/collections.py", line 18, in create
    return self.api_call.post(Collections.RESOURCE_PATH, schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/typesense/api_call.py", line 153, in post
    return self.make_request(session.post, endpoint, as_json,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/typesense/api_call.py", line 116, in make_request
    raise ApiCall.get_exception(r.status_code)(r.status_code, error_message)
typesense.exceptions.ObjectAlreadyExists: [Errno 409] A collection with name `commands` already exists.

[2023-12-27T21:42:49] ERROR:    Application startup failed. Exiting.

```

my .env file
```
HA_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwNDFjOTJjMTFiYTI0NGFjYWU2MjUyYmE0YjM0NGQ3NiIsImlhdyadayada>
HA_URL="http://192.168.1.250:8123"
WAC_PORT=9001
FORWARD_TO_CHAT=True
COMMAND_FINAL_HA_FORWARD="Ask Echo"

COMMAND_LEARNED="Learned new command."
COMMAND_CORRECTED="I used command"
COMMANDS_TO_SKIP='["Ask GPT", "Ask Echo"]'
FEEDBACK=True
```

**Comment by kovrom** [comment]
Most likely it has to do with  WAC_PORT=9001. So either clone fresh and build with this .env file but remove  WAC_PORT=9001
or try to add RUN_MODE=dev to your .env file if you are insisting on using WAC_PORT=9001.

**Comment by jazzmonger** [comment]
RUN_MODE=dev doesnt work.

which .env file????

**Comment by kovrom** [comment]
So if someone else will run into this issue. TLDR: make sure not to use WAC_PORT override in the .env. And make sure you have port 9000 not used by anything else.
